name: Build and release Avg
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
    
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build binary
        run: |
          make build
      - name: Set binary absolute path
        run: |
          binary_path=$(pwd)/main
          echo "BIN_PATH=${binary_path}" >> $GITHUB_ENV
      
      - name: Check commit tag format
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [[ ! $TAG_NAME =~ ^v[0-9]+\.0$ ]]; then
            git tag -d "$TAG_NAME"  
            git push origin --delete "$TAG_NAME"
            echo "Error: Tag $TAG_NAME does not match the required format 'vX.0'."
            exit 1
          fi
          echo "Tag $TAG_NAME is valid."
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create avg-${{ github.ref_name }}-x86_64 \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes
      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload avg-${{ github.ref_name }}-x86_64 ${{ env.BIN_PATH }} --clobber

      - name: Install s2i
        run: |
           wget https://github.com/openshift/source-to-image/releases/download/v1.1.14/source-to-image-v1.1.14-874754de-linux-386.tar.gz
           tar -xvf source-to-image-v1.1.14-874754de-linux-386.tar.gz
           sudo mv s2i /usr/local/bin
 
      - name: Create image
        run: |
           sudo s2i build . quay.io/rh-ee-smartand/mygo-s2i-builder quay.io/rh-ee-smartand/mygo-avg-app
           sudo docker login -u rh-ee-smartand -p ${{ secrets.QUAY_PASSWORD }} quay.io
           sudo docker push quay.io/rh-ee-smartand/mygo-avg-app

      - name: Install OCP
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Deploy on OCP
        run: |
            oc login --token=${{ secrets.OC_TOCKEN }} --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
            oc project rh-ee-sakkulka-dev
            oc create deployment mygo-avg11 --image=quay.io/rh-ee-smartand/mygo-avg-app
            sleep 10
            oc expose deployment mygo-avg11 --port 3100
            sleep 10
            oc expose service mygo-avg11
            oc get routes

