name: Build and release Avg
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate changelog
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          OLD_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          git log --pretty='%h - %s (%an)' ${OLD_TAG}..${NEW_TAG}
          make changelog | tee -a changelog
          cat changelog
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build binary
        run: |
          make build
      - name: Set binary absolute path
        run: |
          binary_path=$(pwd)/main
          echo "BIN_PATH=${binary_path}" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          cat changelog
          gh release create avg-${{ github.ref_name }}-x86_64 \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --notes-file changelog
      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload avg-${{ github.ref_name }}-x86_64 ${{ env.BIN_PATH }} --clobber

      - name: Install s2i
        run: |
           wget https://github.com/openshift/source-to-image/releases/download/v1.1.14/source-to-image-v1.1.14-874754de-linux-386.tar.gz
           tar -xvf source-to-image-v1.1.14-874754de-linux-386.tar.gz
           sudo mv s2i /usr/local/bin
 
      - name: Create image
        run: |
           sudo s2i build . quay.io/rh-ee-smartand/mygo-s2i-builder quay.io/rh-ee-smartand/mygo-avg-app
           sudo docker login -u rh-ee-smartand -p ${{ secrets.QUAY_PASSWORD }} quay.io
           sudo docker push quay.io/rh-ee-smartand/mygo-avg-app

      - name: Install OCP
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Deploy on OCP
        run: |
            oc login --token=${{ secrets.OC_TOCKEN }} --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
            oc project rh-ee-sakkulka-dev
            oc create deployment mygo-avg11 --image=quay.io/rh-ee-smartand/mygo-avg-app
            sleep 10
            oc expose deployment mygo-avg11 --port 3100
            sleep 10
            oc expose service mygo-avg11
            oc get routes

