name: Build and release Avg
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate changelog
        run: |
          make changelog | tee -a changelog
          cat changelog
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build binary
        run: |
          make build
      - name: Set binary absolute path
        run: |
          binary_path=$(pwd)/main
          echo "BIN_PATH=${binary_path}" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          cat changelog
          gh release create avg-${{ github.ref_name }}-x86_64 \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --notes-file changelog
      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload avg-${{ github.ref_name }}-x86_64 ${{ env.BIN_PATH }} --clobber

      - name: Install s2i
        run: |
          sudo apt install -y s2i
          sudo apt install -y docker
 
      - name: Create image
        run: |
           sudo s2i build . quay.io/rh-ee-smartand/mygo-s2i-builder quay.io/rh-ee-smartand/mygo-avg-app
           sudo docker login -u rh-ee-smartand -p ${{ secrets.QUAY_PASSWORD }} quay.io
           sudo docker push quay.io/rh-ee-smartand/mygo-avg-app

